config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:show, :index, :new, :create, :destroy] do
    resources :doses, only: [:create, :new]
  end

  resources :doses, only: [:destroy]

  resources :ingredients, only: [:show]

  mount Attachinary::Engine => "/attachinary"

  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    Cocktail.find(params[:id]).destroy
    redirect_to cocktails_path
  end

  private


  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @ingredients = Ingredient.all
      render 'cocktails/new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def destroy
    ingredient_to_destory = Ingredient.find(params[:id])
    ingredient_to_destory.destroy
    redirect_to cocktail_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, placeholder: "Mojito" %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/cocktails/index.html.erb
<h1 class="main-title">Fancy Cocktails</h1>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card text-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= cl_image_path cocktail.photo? ? cocktail.photo.path : 'http://www.seriouseats.com/images/2014/11/20141104-cocktail-party-old-fashioneds-holiday-vicky-wasik-3.jpg', height: 300, width: 400, crop: :fill %>)">

          <div class="card-category"><%= cocktail.name %></div>
        <div class="card-description">
          <h2><% cocktail.doses.each do |dose| %></h2>
          <p><%= dose.description %></p>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktails) do |cocktail| %>
    <ul>
      <li><%= @cocktail.name %></li>
      <li><%= @cocktail.dose %></li>
    </ul>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <% if @cocktail.photo? %>
        <%= cl_image_tag @cocktail.photo.path, width: 200, height: 300, crop: :fill %>
      <% end %>
      <ul class="list-unstyled">
        <% @cocktail.doses.each do |dose| %>
          <li><%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %> : <%= dose.description %> <%= link_to "<i class='fa fa-close'></i>".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% end %>
      </ul>
      <br>
      <% if @dose.errors.any? %>
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description %>
        <%= f.input :ingredient_id, collection: @ingredients %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Delete cocktail', cocktail_path(@cocktail), method: :delete %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |d| %>
    <%= d.input :description, placeholder: "dose" %>
    <%= d.button :submit, class: "btn btn-primary"  %>
<% end %>

<!-- <form action="/cocktails/1/doses" method="post"></form>
 -->

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Dose</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<h1>Les cocktails avec du <%= @ingredient.name %> sont :</h1>
<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </body>
</html>